#!/usr/bin/env bash
#transfesrs a file via ssh using scp
function tranfer_file()
{
	if [ "$#" -ne 4 ]; then
		echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
		return 1
	fi
	scp -o StrictHostKeyChecking=no  -i "$4" "$1" "$3"@"$2":~/
}
tranfer_file "$@"
