#!/usr/bin/env bash
# fix nginx listen port 80
# note the restart command should be used instead of the start commad
# because is nginx is already runnin the start command will do nothing
# and as such the changes will not apply
# but restart kills the service and starts it again
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
