#!/usr/bin/env bash
# fix nginx listen port 80 using symbolic link
# note the restart command should be used instead of the start comma
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
