#!/usr/bin/env bash
# bash script to set up apache2 and php
sudo apt-get update
sudo apt-get install apache2 -y
sudo apt-get install php libapache2-mod-php php-mysql -y
sudo systemctl restart apache2
sudo systemctl enable apache2
sudo systemctl status apache2
