#!/usr/bin/env bash
# uses file containing my ssh key to authenticate with my server
cat ~/.ssh/school | ssh ubuntu@100.26.237.35 "mkdir -p ~/.ssh && cat >> ~/.ssh/authorized_keys""mkdir -p ~/.ssh && cat >> ~/.ssh/authorized_keys"
